services:
  postgres:
    image: postgres:15
    container_name: postgres-ruby
    environment:
      POSTGRES_DB: ruby_dev
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pg_data:/var/lib/postgresql/data'

volumes:
  pg_data:
