// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "common": {
    "loading": "Завантаження...",
    "error": "Помилка",
    "success": "Успіх",
    "cancel": "Скасувати",
    "save": "Зберегти",
    "delete": "Видалити",
    "edit": "Редагувати",
    "close": "Закрити",
    "confirm": "Підтвердити",
    "back": "Назад",
    "next": "Далі",
    "previous": "Попередня",
    "search": "Пошук",
    "filter": "Фільтр",
    "clear": "Очистити",
    "unknown": "Невідомо",
    "all": "Всі"
  }
};
export default messages;